# Generated by Django 4.0.5 on 2022-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civi_api', '0002_alter_fact_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='fact',
            name='flags',
            field=models.CharField(choices=[('c', 'Civil'), ('v', 'Voting'), ('s', 'Slavery'), ('z', 'Citizenship')], max_length=1),
        ),
    ]
