# Generated by Django 4.0.5 on 2022-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civi_api', '0003_alter_fact_fact_alter_fact_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
