# Generated by Django 4.0.5 on 2022-06-22 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civi_api', '0004_fact_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='source',
            field=models.URLField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fact',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fact',
            name='progress',
            field=models.BooleanField(blank=True),
        ),
    ]
