# Generated by Django 4.0.5 on 2022-06-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civi_api', '0005_fact_source_alter_fact_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
